### ISSUE TITLE
Use Buttons

### ISSUE THREAD

**Issue by TechPro424** [ghostdevv/djs-ticketsystem#11]
Instead of a `createTicket` method, there could be a `deployTicket` method which sends an embed in a channel with a button that users can click to open the ticket.

Note: This is possible only if #9 is closed

**Comment by ghostdevv** [comment]
When #9 is complete you will be able to do button tickets just like you could with reaction tickets in v12, just create a button and when a interaction event for that button comes in respond to it by creating a ticket

we might include baked in support for button tickets to make it easier on the developer to create them but it's not 100% yet

**Comment by TechPro424** [comment]
Yes, that baked in support is what I am talking about

**Comment by ghostdevv** [comment]
I have added a example with buttons to the todo, I am not sure if we will have it baked in or not at the moment
You can view the todo: https://github.com/ghostdevv/djs-ticketsystem/issues/9
