### ISSUE TITLE
Is the config in JSON format, or JS?

### ISSUE THREAD

**Issue by DankMemezx** [ghostdevv/djs-ticketsystem#14]
I've tried both JSON and JS for the config (default, provided in readme), and it gives errors no matter which one it is. It's confusing. any help?

**Comment by ghostdevv** [comment]
Can you please post your error?

**Comment by DankMemezx** [comment]
> Can you please post your error?

![image](https://user-images.githubusercontent.com/77675720/138760883-12bbd222-a4ca-4bb5-8aee-068e8dae0f44.png) - JavaScript


![image](https://user-images.githubusercontent.com/77675720/138760964-e438237d-46e1-4e25-8c5c-ebccd9960fb9.png) - JSON (code is same as JS)

**Comment by ghostdevv** [comment]
Hi, you don't need to put the default config anywhere - you can just include the config you want in specific places and it will overwrite the default where it has to

- You can pass config in the createTicket function
- You can use the defaults option to set default options

all of this can be seen in the docs <https://github.com/ghostdevv/djs-ticketsystem/blob/main/readme.md>

Feel free to join the discord if you are still struggling: https://discord.gg/2Vd4wAjJnm
