### ISSUE TITLE
custom message 

### ISSUE THREAD

**Issue by seandadonntech** [ghostdevv/djs-ticketsystem#7]
hello I'm am trying to make custom message for my ticket user can you help me please>

**Comment by ghostdevv** [comment]
@seandadonntech Custom message how? Like when you open the ticket?

**Comment by seandadonntech** [comment]
yes im trying to make my own custom message

**Comment by seandadonntech** [comment]
Do I put the config in the json file?

**Comment by ghostdevv** [comment]
in the config you want like
```js
.createTicket({
    owner: message.author,
    openMessage: {
       embed: new Discord.MessageEmbed().setDescription('description');
    }
})
```

something like this, if you want text instead you can do `text` instead of embed

@seandadonntech
